# Generated by Django 4.2.27 on 2025-12-25 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('location_id', models.CharField(help_text='ID único de la subcuenta de GHL', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('api_key', models.CharField(help_text='Token de autorización para validar webhooks', max_length=255)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghl_contact_id', models.CharField(help_text='ID del contacto/producto en GHL', max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('zona', models.CharField(db_index=True, max_length=255)),
                ('habitaciones', models.IntegerField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('vendido', 'Vendido')], default='activo', max_length=50)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='ghl_middleware.agencia')),
            ],
            options={
                'indexes': [models.Index(fields=['zona', 'precio'], name='ghl_middlew_zona_27e9ed_idx')],
                'unique_together': {('agencia', 'ghl_contact_id')},
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghl_contact_id', models.CharField(help_text='ID del contacto en GHL', max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('presupuesto_maximo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('zona_interes', models.CharField(max_length=255)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='ghl_middleware.agencia')),
            ],
            options={
                'unique_together': {('agencia', 'ghl_contact_id')},
            },
        ),
    ]
