# Generated by Django 4.2.27 on 2026-01-01 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_middleware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHLToken',
            fields=[
                ('location_id', models.CharField(help_text='ID de la subcuenta que instaló la app', max_length=255, primary_key=True, serialize=False)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_type', models.CharField(max_length=50)),
                ('expires_in', models.IntegerField(default=86400)),
                ('scope', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='agencia',
            name='active',
            field=models.BooleanField(default=True, help_text='Desactiva la agencia si deja de pagar'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agencia',
            name='api_key',
            field=models.CharField(blank=True, help_text='Token de autorización para validar webhooks (Opcional si usas OAuth)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, default='Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='presupuesto_maximo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='zona_interes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='habitaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='zona',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
