# Generated by Django 4.2.27 on 2026-01-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_middleware', '0002_ghltoken_agencia_active_cliente_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='propiedad',
            name='ghl_middlew_zona_27e9ed_idx',
        ),
        migrations.AddField(
            model_name='cliente',
            name='habitaciones_minimas',
            field=models.IntegerField(default=0, help_text='Nº mínimo de habitaciones que busca el cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='propiedades_interes',
            field=models.ManyToManyField(blank=True, help_text='Historial de propiedades que hacen match con este cliente', related_name='interesados', to='ghl_middleware.propiedad'),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='api_key',
            field=models.CharField(blank=True, help_text='Token de autorización (Opcional si usas OAuth)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ghl_contact_id',
            field=models.CharField(help_text='ID del CONTACTO en GHL', max_length=255),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='ghl_contact_id',
            field=models.CharField(help_text='ID del REGISTRO (Record ID) del Custom Object en GHL', max_length=255),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='habitaciones',
            field=models.IntegerField(default=0, help_text='Nº de habitaciones que tiene la propiedad'),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['zona', 'precio', 'habitaciones'], name='ghl_middlew_zona_14af17_idx'),
        ),
    ]
