# Generated by Django 4.2.27 on 2026-01-22 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_middleware', '0003_remove_propiedad_ghl_middlew_zona_27e9ed_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameIndex(
            model_name='propiedad',
            new_name='ghl_middlew_zona_id_fd59ea_idx',
            old_name='ghl_middlew_zona_14af17_idx',
        ),
        migrations.AddField(
            model_name='cliente',
            name='animales',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No'), ('ind', 'Indiferente')], default='ind', max_length=3),
        ),
        migrations.AddField(
            model_name='cliente',
            name='balcon',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No'), ('ind', 'Indiferente')], default='ind', max_length=3),
        ),
        migrations.AddField(
            model_name='cliente',
            name='garaje',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No'), ('ind', 'Indiferente')], default='ind', max_length=3),
        ),
        migrations.AddField(
            model_name='cliente',
            name='metrosMinimo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='animales',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No'), ('ind', 'Indiferente')], default='ind', max_length=3),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='balcon',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No'), ('ind', 'Indiferente')], default='ind', max_length=3),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='garaje',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No'), ('ind', 'Indiferente')], default='ind', max_length=3),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='imagenesUrl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='metros',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='zona_interes',
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('vendido', 'Vendido'), ('noficial', 'No Oficial')], default='activo', max_length=10),
        ),
        migrations.AddField(
            model_name='zona',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='ghl_middleware.municipio'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='ghl_middleware.provincia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='zona_interes',
            field=models.ManyToManyField(blank=True, max_length=255, null=True, related_name='clientes', to='ghl_middleware.zona'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='zona',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades', to='ghl_middleware.zona'),
        ),
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together={('provincia', 'nombre')},
        ),
    ]
