# Generated by Django 4.2.27 on 2026-01-23 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_middleware', '0004_municipio_provincia_zona_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='propiedad',
            name='ghl_middlew_zona_id_fd59ea_idx',
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagenesUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades', to='ghl_middleware.zona'),
        ),
    ]
