# Generated by Django 4.2.27 on 2026-01-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_middleware', '0005_remove_propiedad_ghl_middlew_zona_id_fd59ea_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='patioInterior',
            field=models.CharField(choices=[('si', 'Si'), ('ind', 'Indiferente')], default='ind', max_length=3),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='patioInterior',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='animales',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='balcon',
            field=models.CharField(choices=[('si', 'Si'), ('ind', 'Indiferente')], default='ind', max_length=3),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='garaje',
            field=models.CharField(choices=[('si', 'Si'), ('ind', 'Indiferente')], default='ind', max_length=3),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='animales',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='balcon',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='garaje',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagenesUrl',
            field=models.JSONField(default=list),
        ),
    ]
