# Generated by Django 4.2.27 on 2026-01-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_middleware', '0006_cliente_patiointerior_propiedad_patiointerior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencia',
            name='association_type_id',
            field=models.CharField(blank=True, help_text='ID de asociación dinámico para esta subcuenta (vía GHL API)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='zona_interes',
            field=models.ManyToManyField(blank=True, max_length=255, related_name='clientes', to='ghl_middleware.zona'),
        ),
    ]
