# Generated by Django 4.2.27 on 2026-01-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_middleware', '0007_agencia_association_type_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='zona_interes',
            field=models.ManyToManyField(blank=True, max_length=255, null=True, related_name='clientes', to='ghl_middleware.zona'),
        ),
    ]
