# Generated by Django 4.2.27 on 2026-01-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_middleware', '0008_alter_cliente_zona_interes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencia',
            name='association_type_id',
        ),
    ]
