# Generated by Django 4.2.27 on 2026-01-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_middleware', '0009_remove_agencia_association_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencia',
            name='association_type_id',
            field=models.CharField(blank=True, help_text='ID de asociación dinámico para esta subcuenta (vía GHL API)', max_length=255, null=True),
        ),
    ]
