# Generated by Django 4.2.27 on 2026-02-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_middleware', '0010_agencia_association_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='zona',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
