# Generated by Django 4.2.27 on 2026-02-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ghl_middleware",
            "0011_alter_municipio_nombre_alter_provincia_nombre_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="agencia",
            name="ghl_custom_field_cliente_zona",
            field=models.CharField(
                blank=True,
                help_text="ID del custom field de zona en Contactos de GHL",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agencia",
            name="ghl_custom_field_propiedad_zona",
            field=models.CharField(
                blank=True,
                help_text="ID del custom field de zona en el Custom Object Propiedad de GHL",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agencia",
            name="umbral_featured",
            field=models.DecimalField(
                decimal_places=2,
                default=500000,
                help_text="Precio minimo para marcar una propiedad como destacada (isFeatured)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="zona_interes",
            field=models.ManyToManyField(
                blank=True, related_name="clientes", to="ghl_middleware.zona"
            ),
        ),
        migrations.AlterField(
            model_name="propiedad",
            name="estado",
            field=models.CharField(
                choices=[
                    ("activo", "Activo"),
                    ("vendido", "Vendido"),
                    ("noficial", "No Oficial"),
                ],
                default="activo",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["agencia", "presupuesto_maximo"],
                name="cli_agencia_presupuesto_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="propiedad",
            index=models.Index(
                fields=["agencia", "estado", "precio"],
                name="prop_agencia_estado_precio_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="propiedad",
            index=models.Index(
                fields=["agencia", "zona"], name="prop_agencia_zona_idx"
            ),
        ),
    ]
