# Generated by Django 5.2.11 on 2026-02-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ghl_middleware", "0012_agencia_ghl_custom_field_cliente_zona_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cliente",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="propiedad",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="agencia",
            name="property_object_id",
            field=models.CharField(
                blank=True,
                help_text="ID del Custom Object 'Propiedad' en GHL (cacheado del setup)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="sync_error",
            field=models.TextField(
                blank=True, default="", help_text="Ultimo error de sincronizacion"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente de sync"),
                    ("syncing", "Sincronizando"),
                    ("synced", "Sincronizado"),
                    ("error", "Error de sync"),
                ],
                db_index=True,
                default="synced",
                help_text="Estado de sincronizacion con GHL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="sync_error",
            field=models.TextField(
                blank=True, default="", help_text="Ultimo error de sincronizacion"
            ),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente de sync"),
                    ("syncing", "Sincronizando"),
                    ("synced", "Sincronizado"),
                    ("error", "Error de sync"),
                ],
                db_index=True,
                default="synced",
                help_text="Estado de sincronizacion con GHL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="ghl_contact_id",
            field=models.CharField(
                blank=True,
                help_text="ID del CONTACTO en GHL",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="propiedad",
            name="ghl_contact_id",
            field=models.CharField(
                blank=True,
                help_text="ID del REGISTRO (Record ID) del Custom Object en GHL",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="cliente",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ghl_contact_id__isnull", False)),
                fields=("agencia", "ghl_contact_id"),
                name="unique_cliente_agencia_ghl_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="propiedad",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ghl_contact_id__isnull", False)),
                fields=("agencia", "ghl_contact_id"),
                name="unique_propiedad_agencia_ghl_id",
            ),
        ),
    ]
