# Generated by Django 4.2.27 on 2026-03-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_middleware', '0013_sync_to_ghl_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pendiente de sync'), ('syncing', 'Sincronizando'), ('synced', 'Sincronizado'), ('error', 'Error de sync')], db_index=True, default='pending', help_text='Estado de sincronizacion con GHL', max_length=20),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagenesUrl',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pendiente de sync'), ('syncing', 'Sincronizando'), ('synced', 'Sincronizado'), ('error', 'Error de sync')], db_index=True, default='pending', help_text='Estado de sincronizacion con GHL', max_length=20),
        ),
    ]
