# Generated by Django 4.2.27 on 2026-03-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_middleware', '0014_alter_cliente_sync_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='propiedad',
            name='prop_agencia_zona_idx',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='zona',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='zonas',
            field=models.ManyToManyField(blank=True, related_name='propiedades', to='ghl_middleware.zona'),
        ),
    ]
