# Generated by Django 4.2.27 on 2026-03-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_middleware', '0015_remove_propiedad_prop_agencia_zona_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='calle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
