# Generated by Django 4.2.27 on 2026-04-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_middleware', '0016_propiedad_calle_propiedad_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
