# Generated by Django 4.2.27 on 2026-04-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_middleware', '0017_propiedad_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
