# Generated by Django 4.2.27 on 2026-04-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_middleware', '0018_propiedad_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencia',
            name='umbral_featured',
        ),
    ]
